version: "3.8"

services:
  node:
    container_name: music-store-node
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    container_name: music-store-mongo
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
